////Generated by Prefab3D 2.143, Fri May 13 07:26:12 GMT-0500 2016. www.closier.nl/prefab
package asd
{
	import asd.ASDReader;

	public class AxeData {

		[Embed(source="../../assets/AxeData.asd", mimeType="application/octet-stream")]
		private var AxeDataASD:Class;

		public function get geometryData():void
		{
			ASDReader.decodeGeometry(new AxeDataASD());
		}

	}
}